October 2020 Release Notes
livingdocsIO/livingdocs-release-notes pull request #39
Opened 2020-09-22 09:48 UTC by DaRaFF

2020-09-29 11:39 UTC, benib commented on releases/release-2020-10.md
> +One can register and use a custom display filter as a Vue component (e.g. on a dashboard).
```suggestion
One can register a Vue component as a custom display filter (e.g. on a dashboard).
```

2020-09-29 11:47 UTC, benib requested changes

2020-09-29 11:47 UTC, benib commented on releases/release-2020-10.md
> +Implement [Doc Includes](https://docs.livingdocs.io/evaluation-guide/intro#summary-of-a-doc-include) with Vue.
Since the thing one can do with Vue is the editor customization part, should we link to https://docs.livingdocs.io/reference-docs/includes/editor_customization ? instead
And: we need to update the docs before these release notes are sent out.

2020-09-29 11:47 UTC, benib commented on releases/release-2020-10.md
> +  * Show message when no document has an image reference [livingdocs-editor #3826](https://github.com/livingdocsIO/livingdocs-editor/pull/3826) :gift:
```suggestion
  * Show message when an image is not used in any document [livingdocs-editor #3826](https://github.com/livingdocsIO/livingdocs-editor/pull/3826) :gift:
```

2020-09-29 11:47 UTC, benib commented on releases/release-2020-10.md
> +  * Store any concept properties returned from the server [livingdocs-editor #3837](https://github.com/livingdocsIO/livingdocs-editor/pull/3837) :gift:
```suggestion
  * iMatrics: Store any concept properties returned from the server [livingdocs-editor #3837](https://github.com/livingdocsIO/livingdocs-editor/pull/3837) :gift:
```

2020-09-29 11:47 UTC, benib commented on releases/release-2020-10.md
> +  * Updates suggestion in realtime [livingdocs-editor #3817](https://github.com/livingdocsIO/livingdocs-editor/pull/3817) :gift:
```suggestion
  * iMatrics: Update suggestion in realtime in the dashboard [livingdocs-editor #3817](https://github.com/livingdocsIO/livingdocs-editor/pull/3817) :gift:
```

2020-09-29 11:52 UTC, gabrielhase commented on releases/release-2020-10.md
> +- Proof of concept: Whenever an image is uploaded to Livingdocs, it's also uploaded to WoodWing assets with some basic metadata.
why do you call it proof of concept?

2020-09-29 11:53 UTC, gabrielhase commented on releases/release-2020-10.md
> +
I would mention the Livingdocs to WoodWing Studio project as a sidenote here:
```
Related: we also implemented an open-source boilerplate for a Livingdocs to WoodWing Studio transformer as an AWS serverless app. Find the code on our Github repo: https://github.com/livingdocsIO/livingdocs-to-woodwing-exporter
```

2020-09-29 11:53 UTC, gabrielhase commented on releases/release-2020-10.md
> +
I remember seeing an animated gif of this somewhere. Would be nice to add this here

2020-09-29 11:55 UTC, gabrielhase commented on releases/release-2020-10.md
> +For example register custom image services in in the downstream (instead of adding them to the `livingdocs-framework`).
That is the worst description I've ever read 😆 
- I don't know what "Image Service 2.0" is in the first place -> that should go into the description
- Never start a description with "for example"

2020-09-29 11:57 UTC, gabrielhase commented on releases/release-2020-10.md
> +- The rendering is separated from the imageService itself and renderStrategies can be defined via configuration.
an example code block would help a lot

2020-09-29 11:57 UTC, gabrielhase commented on releases/release-2020-10.md
> +- New image service configuration like a `imgTagRenderStrategy` are available
Please list all of them and what they do

2020-09-29 11:58 UTC, gabrielhase commented on releases/release-2020-10.md
> +- Added a backgroundImage render strategy with responsive behaviour
I know for a fact that responsive bg images are hard. Please describe which strategy you used here

2020-09-29 11:58 UTC, gabrielhase commented on releases/release-2020-10.md
> +Look [here](https://github.com/livingdocsIO/livingdocs-framework/pull/497) fore more infos on how the new image services can be configured.
We should def. do documentation for this and not just have a PR

2020-09-29 12:55 UTC, gabrielhase commented on releases/release-2020-10.md
> +## Public API - Support client defined documentId in the import API #3145 :gift:
This needs documentation (update) as well

2020-09-29 13:01 UTC, gabrielhase requested changes
The `Image Service 2.0` and `custom ids in import API` features need documentation.

2020-09-29 14:43 UTC, DaRaFF commented on releases/release-2020-10.md
> +- Proof of concept: Whenever an image is uploaded to Livingdocs, it's also uploaded to WoodWing assets with some basic metadata.
Because you had this passage in your PR :-)

2020-09-30 08:23 UTC, DaRaFF commented on releases/release-2020-10.md
> +  * Store any concept properties returned from the server [livingdocs-editor #3837](https://github.com/livingdocsIO/livingdocs-editor/pull/3837) :gift:
Its a sub menu of Imatrics, therefore it makes no sense to add an Imatrics prefix again.

2020-09-30 08:27 UTC, DaRaFF commented on releases/release-2020-10.md
> +
@benib is there somewhere an animated gif?

2020-09-30 08:29 UTC, DaRaFF commented on releases/release-2020-10.md
> +- The rendering is separated from the imageService itself and renderStrategies can be defined via configuration.
We don't want to blow up the release notes. Examples for new features should be in our documentation. I asked already @peyerluk to add some documentation.

2020-09-30 08:29 UTC, DaRaFF commented on releases/release-2020-10.md
> +- New image service configuration like a `imgTagRenderStrategy` are available
Same here, not in the release notes.

2020-09-30 08:30 UTC, DaRaFF commented on releases/release-2020-10.md
> +- Added a backgroundImage render strategy with responsive behaviour
//cc @peyerluk

2020-09-30 08:30 UTC, DaRaFF commented on releases/release-2020-10.md
> +Look [here](https://github.com/livingdocsIO/livingdocs-framework/pull/497) fore more infos on how the new image services can be configured.
It's already ordered.

2020-09-30 08:35 UTC, DaRaFF commented on releases/release-2020-10.md
> +## Public API - Support client defined documentId in the import API #3145 :gift:
@marcbachmann can you write some documentation (update) for that?

2020-09-30 08:47 UTC, DaRaFF commented on releases/release-2020-10.md
> +Implement [Doc Includes](https://docs.livingdocs.io/evaluation-guide/intro#summary-of-a-doc-include) with Vue.
I would love it!

2020-09-30 08:49 UTC, DaRaFF commented on releases/release-2020-10.md
> +Implement [Doc Includes](https://docs.livingdocs.io/evaluation-guide/intro#summary-of-a-doc-include) with Vue.
Have you time for that in the next few days @benib ?

2020-10-19 09:44 UTC, peyerluk commented on releases/release-2020-10.md
> +We massively improved the image uploading process. The improvements are:
-> We improved the image uploading process for cases when the user needs to provide image metadata before an image can be uploaded.

2020-10-19 09:49 UTC, peyerluk approved these changes
Looks good. 

And I still have to provide the image service 2.0 documentation.

2020-10-22 05:55 UTC, merged