October 2020 Release Notes
livingdocsIO/livingdocs-release-notes pull request #41
Opened 2020-12-15 14:01 UTC by DaRaFF

Issue: https://github.com/livingdocsIO/livingdocs-planning/issues/4098

2020-12-29 15:16 UTC, mokimo commented on releases/release-2020-12.md
> +## Security - User access tokens require valid cookies
@DaRaFF I added a small paragraph on what's been causing issues for T-Online and the Bluewin downstream.

@gabrielhase if you have anything to add after you did the integration let me know!

2020-12-30 10:52 UTC, mokimo commented
Custom indexes breaking changes are missing:
https://github.com/livingdocsIO/livingdocs-server/pull/3185

2020-12-30 11:20 UTC, mokimo commented
Breaking changes are missing - Migrating an existing SSO Login:
https://github.com/livingdocsIO/livingdocs-planning/issues/4140#issuecomment-752400198

2021-01-04 09:22 UTC, gabrielhase commented on releases/release-2020-12.md
> +With this release, we allow a user to inline add/edit components and its settings (e.g. images) in the editor with your mobile.
I would not mention `images` since the cropping is not working. Unless someone is reviewing my PR for srcissors ;)

2021-01-04 09:23 UTC, gabrielhase commented on releases/release-2020-12.md
> +With this release, we allow a user to inline add/edit components and its settings (e.g. images) in the editor with your mobile.
And maybe mention that this is a MVP and we will gradually improve this in future releases

2021-01-04 09:24 UTC, gabrielhase commented on releases/release-2020-12.md
> +Editable teasers are embedded editable livingdocs components. Technically editable teasers are doc-includes returning livingdocs components, which can be edited like any other component. For more inf
It should be mentioned that editable teasers do not work with the render pipeline v1 and are thus not usable for most of our customers. This should be fixed in an upcoming release. Again, a MVP or "epxerimental" mention would probably make sense.

2021-01-04 09:25 UTC, gabrielhase commented on releases/release-2020-12.md
> +When selecting text in the editor, the link tool in the editable toolbar allows to link to documents instead of URLs only. The input field is a combined input and detects if you want to search, or if
We should mention that the delivery needs a strategy to redirect id route patterns in order for inline links to work in the delivery.

2021-01-04 09:26 UTC, gabrielhase commented on releases/release-2020-12.md
> +We introduce videos in Livingdocs with these abilities:
I didn't test this one, but from what I heard this should also def. get an "experimental" tag.

2021-01-04 09:28 UTC, gabrielhase commented on releases/release-2020-12.md
> +## Migrations from Referenced to Embedded Design via UI :tada:
This is not really a highlight. I would move that to the small improvements section and only mention that we support bumps from ref. designs to embedded designs in the UI now.
(The whole feature of embedded designs is not finished yet, since we still don't have an asset workflow in Livingdocs. We should migrate customers there but we should do it ourselves and not let them do it, at least for now)

2021-01-04 09:53 UTC, gabrielhase commented on releases/release-2020-12.md
> +## More Secure Authentication Workflow :tada:
please add the SSO specific documentation I sent you

2021-01-04 09:53 UTC, gabrielhase commented on releases/release-2020-12.md
> +We integrated Airship for push notifications.
maybe a link to the airship service would be nice

2021-01-04 10:07 UTC, gabrielhase commented on releases/release-2020-12.md
> +- :fire: Existing messages from `bull` won't be processed anymore.
do we know who is using `bull`

2021-01-04 13:26 UTC, gabrielhase commented on releases/release-2020-12.md
> +* Operation Screen
this would be the place for the embedded design migration

2021-01-04 13:28 UTC, gabrielhase requested changes
I would move a lot of things to "Internal Changes" or a new "MVP - experimental" section. In any case Video and Editable Teasers.

2021-01-08 17:04 UTC, DaRaFF commented on releases/release-2020-12.md
> +## More Secure Authentication Workflow :tada:
https://github.com/livingdocsIO/livingdocs-planning/issues/4140#issuecomment-752400198

2021-01-13 14:42 UTC, DaRaFF commented on releases/release-2020-12.md
> +- :fire: Existing messages from `bull` won't be processed anymore.
Every customer

2021-02-01 08:31 UTC, merged