March 2021 Release Notes
livingdocsIO/livingdocs-release-notes pull request #43
Opened 2021-02-13 14:45 UTC by DaRaFF

Issue: https://github.com/livingdocsIO/livingdocs-planning/issues/4221

2021-03-26 07:48 UTC, gabrielhase commented on releases/release-2021-03.md
> +When the user uploads images or videos, a new Upload Center is visible in the bottom right corner of the screen showing the overall upload status and an error indication.
Some rephrasing:
-> `When the user uploads images or videos, a new Upload Center is visible in the bottom right corner of the editor screen allowing the users to continue their work in the document while assets are uploaded in parallel in the background. If an error with any of the uploads happens it is shown and logged in the upload center.`

2021-03-26 08:01 UTC, gabrielhase commented on releases/release-2021-03.md
> +Allow to connect/integrate external asset services (e.g. Unsplash, Shutterstock, Pixabay, ...) as a Media Source in the Livingdocs Media Library. Working with a Media Source in Livingdocs feels the s
Add the following sentence: `The examples from the Livingdocs core all include free open source platforms, but of course one could also use media sources to integrate external DAM systems that might already be present in a publishers system landscape and by that consolidate the asset workflow for the journalists into Livingdocs.`

2021-03-26 08:02 UTC, gabrielhase commented on releases/release-2021-03.md
> +Define which media library metadata are indexed and define dashboard filter for all metadata (same as for documents and publications).
Prepend the following sentence: `The media library dashboard has now the same search and filter capabilites as the documents dashboard.`

2021-03-26 08:03 UTC, gabrielhase commented on releases/release-2021-03.md
> +The Named Crops feature supports multiple crops per image in a document.
Append the following: `This allows to preset crops on the master images in the media library and on demand overwrite those master crops on the placed image inside an article. Also, the API now provides several crops per image as defined in the named crops settings.`

2021-03-26 08:04 UTC, gabrielhase commented on releases/release-2021-03.md
> +Notifications allow a user to subscribe to specific events of a document (e.g. a publish) and notifies this user via mail/slack when this event happens.
Append: `Currently we support notification of task changes to the task requester and notification of document status changes to the document author.`

2021-03-26 08:05 UTC, gabrielhase commented on releases/release-2021-03.md
> +A simpler way to setup [Article Teasers](https://docs.livingdocs.io/guides/includes-embeds/article_teasers) is introduced. It is based on Includes and the possiblity to define the UI with a `paramsSc
small one: `... the UI with a paramsSchema instead of writing code.`

2021-03-26 08:06 UTC, gabrielhase commented on releases/release-2021-03.md
> +## Media Library - Videos :tada:
We enabled it on the service and it works perfectly fine. Why do we mark this still as experimental?

2021-03-26 08:07 UTC, gabrielhase commented on releases/release-2021-03.md
> +This time we have a huge amount of breaking changes, therefore we grouped the breaking changes into different sections:
`huge` -> `rather high amount`

2021-03-26 08:09 UTC, gabrielhase commented on releases/release-2021-03.md
> +### CLI Script to Fix Group Memberships (post deployment) :fire:
That's a good thing. But why do we mark it as a breaking change?

2021-03-26 08:52 UTC, DaRaFF commented on releases/release-2021-03.md
> +## Media Library - Videos :tada:
I'm not 100% sure, but I can slightly remember that @benib told me that the feature is not production ready. What is your opinion @benib?

2021-03-26 08:55 UTC, DaRaFF commented on releases/release-2021-03.md
> +### CLI Script to Fix Group Memberships (post deployment) :fire:
It's a necessary action we want the customers to do. The breaking changes section is the only section customers know that they MUST execute for a release upgrade. Everything else they can ignore if they want.

2021-03-26 09:11 UTC, gabrielhase commented on releases/release-2021-03.md
> +### Prefix all app Routes with a Project Handle :fire:
While this is a breaking change it is also a feature :) Can we add a section about this to the highlights with a note that we now support deep links in multi-project environments? It's actually a pretty neat feature that a lot of customers will like.

2021-03-26 09:13 UTC, gabrielhase commented on releases/release-2021-03.md
> +- 🔥 Remove coffee-script support in the webpack setup in the editor. We've dropped coffee-script a few years ago, but still kept the webpack loader as not all projects were migrated. From now on we'v
ähem... are we certain that we don't have customers that use coffeescript anymore? We never told customers truly that they need to update now or their downstream is broken. Or are there ways to add coffeescript in a downstream? If so, they should be described here.

2021-03-26 09:14 UTC, gabrielhase commented on releases/release-2021-03.md
> +### Render Pipeline CheerioHtml: Use onTimeRendering by default :fire:
I guess it should be `oneTimeRendering`

2021-03-26 09:17 UTC, gabrielhase commented on releases/release-2021-03.md
> +We worked on document reference extraction. The list below contains public APIs and server APIs with an additional `reference` property in the response. Look into the [documentation](https://github.c
Append the following: `References can be used for static page rendering strategies where updates of references in a page, e.g. teasers, must be identified.`

2021-03-26 09:18 UTC, gabrielhase commented on releases/release-2021-03.md
> +#### Add context object to import endpoints :gift:
That looks like public API, but it is under server API here

2021-03-26 09:20 UTC, gabrielhase commented on releases/release-2021-03.md
> +* SSO: Integrate Azure Active Directory [livingdocs-server #3355](https://github.com/livingdocsIO/livingdocs-server/pull/3355) :gift:
Please also move this to highlights :) and use the following description:
`We support a new SSO connection with Azure Active Directories. This allows customers to setup 2-factor authentication and external group management in Azure AD.`

2021-03-26 09:21 UTC, gabrielhase commented on releases/release-2021-03.md
> +* Tasks: Assign a user to a task [livingdocs-editor #4214](https://github.com/livingdocsIO/livingdocs-editor/pull/4214) :gift:
🎉

2021-03-26 09:25 UTC, gabrielhase commented on releases/release-2021-03.md
> +* Webhooks: Add media library webhooks | extend document.update webhook with metadata filter [livingdocs-server #3359](https://github.com/livingdocsIO/livingdocs-server/pull/3359) :gift:
The webhooks are kind of part of our public API so I would tend to put this there. As this is quite important it seems to small to just mention it down here.

2021-03-26 09:31 UTC, gabrielhase commented on releases/release-2021-03.md
> +  * Rename pusher topic to media and allow - in mediaId [livingdocs-server #3382](https://github.com/livingdocsIO/livingdocs-server/pull/3382) :beetle:
what is pusher doing on the media library?

2021-03-26 09:43 UTC, gabrielhase requested changes
Apart from several text change suggestions I have the following important points:
- why is "Videos" marked experimental? -> This is important for me in communication with clients and leads
- I need to know what dropping coffeescript support means. We can't break downstreams as we never really communicated such a change in a proper way. Not sure if it is breaking but I need to know this before I can sign off on this.
- Marc did new admin screens that contain a complete log viewer and UI for all important jobs (re-indexing, etc.). I couldn't find it in the notes, but it is a game changer for devops and should def. go to the hightlights.

2021-03-26 16:52 UTC, marcbachmann commented on releases/release-2021-03.md
> +  * Rename pusher topic to media and allow - in mediaId [livingdocs-server #3382](https://github.com/livingdocsIO/livingdocs-server/pull/3382) :beetle:
It sends out a notification to the editor on the media entry screen.
e.g. when google vision updates some data.

But I'm not sure how we handle that info at the moment.

2021-03-26 16:53 UTC, marcbachmann commented on releases/release-2021-03.md
> +* SSO: Integrate Azure Active Directory [livingdocs-server #3355](https://github.com/livingdocsIO/livingdocs-server/pull/3355) :gift:
I'd mention openid connect here. Azure AD is just an example integration. There's nothing specific in our code to integration.

2021-03-26 17:10 UTC, benib commented
>     * why is "Videos" marked experimental? -> This is important for me in communication with clients and leads
>

From my perspective it's mostly because of three things:
1. We don't have a video strategy in the framework yet, so we just render the video tag with the storage public URL. That means your bucket has to be public, or you don't see videos played in the Editor
2. There is no good way yet to hook a transcoding pipeline into the system (we will do something with a core metadata plugin you could use right now)
3. We have no integration or knowledge or documentation how you would integrate this with some 3rd party transcoding providers (as we do with images: imgix and others).

So it's not a plug and play thing, we don't have experience nor docs on how to use it in a production environment, and it's not really integrated anywhere yet. If customers plan to use our Media Library for their Video solution, we are ready to help them. But they need to do some additional things to really make it a nice solution.

We can argue if that makes it experimental or not.

2021-03-26 20:14 UTC, gabrielhase commented
@benib IMO we should then transparently mark the shortcoming you mentioned in the release notes, but not mark it as "experimental". Experimental has the sound of buggy to me and that's not really what it is here. As for experience with a feature: we don't have that with any of the new features in a release so that is fine.

2021-03-26 22:55 UTC, benib commented on releases/release-2021-03.md
> +## Media Library - Videos :tada:
From my perspective it's mostly because of three things:

1. We don't have a video strategy in the framework yet, so we just render the video tag with the storage public URL. That means your bucket has to be public, or you don't see videos played in the Editor. This also means it really only works if you render yourself using the JSON. Otherwise you will have S3 public URLs in your delivered HTML. You never want to let your end users load Video Files from S3.
2. There is no good way yet to hook a transcoding pipeline into the system (we will do something with a core metadata plugin you could use right now)
3. We have no integration or experience or documentation how you would integrate this with some 3rd party transcoding/delivery providers (as we do for images: imgix and others).

So it's not a plug and play thing, we don't have experience nor docs on how to use it in a production environment, and it's not really integrated anywhere yet. If customers plan to use our Media Library for their Video solution, we are ready to help them. But they need to do some additional things to really make it a nice solution.

We can argue if that makes it experimental or not.

2021-03-27 12:44 UTC, benib commented on releases/release-2021-03.md
> +## Media Library - Videos :tada:
I added documentation for videos and explained these shortcomings in there. The release notes hold a link to that documentation now.

2021-03-29 06:44 UTC, DaRaFF commented on releases/release-2021-03.md
> +- 🔥 Remove coffee-script support in the webpack setup in the editor. We've dropped coffee-script a few years ago, but still kept the webpack loader as not all projects were migrated. From now on we'v
I don't have any knowledge of a customer using coffee. @marcbachmann is there a possibility to re-add coffee in the downstream?

2021-03-29 07:08 UTC, marcbachmann commented on releases/release-2021-03.md
> +- 🔥 Remove coffee-script support in the webpack setup in the editor. We've dropped coffee-script a few years ago, but still kept the webpack loader as not all projects were migrated. From now on we'v
Customers can still use coffee-script, if they just require `coffeescript` manually (e.g. `node -r coffeescript/register node index.js`). We just don't support it in our glob patterns anymore. We've migrated all the customers away from it already some years ago. I don't know of any customer still using it.

2021-03-29 07:25 UTC, DaRaFF commented
> Marc did new admin screens that contain a complete log viewer and UI for all important jobs (re-indexing, etc.). I couldn't find it in the notes, but it is a game changer for devops and should def. go to the highlights.

@gabrielhase It's in the other changes section, but I can move it up.

2021-03-29 07:33 UTC, DaRaFF commented
> why is "Videos" marked experimental? -> This is important for me in communication with clients and leads

@gabrielhase videos have been moved up to highlights.

2021-03-29 09:51 UTC, peyerluk commented on releases/release-2021-03.md
> +- There is no video provider integration yet (as we do with images, e.g. imgix)
Isn't this the same point as 'There is no video service available'?

2021-03-29 09:54 UTC, peyerluk commented on releases/release-2021-03.md
> +- There is no good way yet to hook a transcoding pipeline into the system (we will do something with a core metadata plugin you could use right now)
T-Online has a transcoding pipeline. So I'm not exactly sure what is meant here? 

> we will do something with a core metadata plugin you could use right now

'will do' and 'use right now' sounds like a contradiction. And what do we mean by this?

2021-03-29 10:00 UTC, peyerluk commented on releases/release-2021-03.md
> +- There is no good way yet to hook a transcoding pipeline into the system (we will do something with a core metadata plugin you could use right now)
Can we go with something along these lines instead?

'Please get in touch if you want to integrate a transcoding pipeline or a video service.'

2021-03-29 10:05 UTC, peyerluk commented on releases/release-2021-03.md
> +
Maybe a short description would help here?

-> We've added tracing support in the server based on opentelemetry.

2021-03-29 10:08 UTC, peyerluk commented on releases/release-2021-03.md
> +We support now editor deep links in multi-project environments. This is the new pattern - `https://0.0.0.0:9000/p/<your-project-handle>/articles/<article-id>`
I would replace:
'We support now editor deep links in multi-project environments'
with
'We changed editor urls to contain the project handle so links work reliably in multi-project setups.'

2021-03-29 10:15 UTC, peyerluk commented on releases/release-2021-03.md
> +- generate document and publication references and store them on the db
I wouldn't use active verbs like 'generate' here as the migration will do this for you.

We could phrase it like this:
- 'The migration removes references from document revisions and stores them per document instead'
- 'The migration generates references on all publications'

2021-03-29 10:22 UTC, peyerluk commented on releases/release-2021-03.md
> +## Breaking Changes - Server + Editor :fire:
Maybe we can move this section a bit further up in this document?

2021-03-29 10:24 UTC, peyerluk commented on releases/release-2021-03.md
> +The html and link directives will in future be data directives, i.e. store object literals. This means that the `getContent()` method will return an object literal and not a string value anymore. The
'The html and link directives will in future be data directives' -> 'The html and link directives are now data directives.'

2021-03-29 10:27 UTC, peyerluk commented on releases/release-2021-03.md
> +
Please add:
The CheerioHtml output renderer for the render-pipeline now uses the frameworks one time rendering
by default which is 10 to 20 times faster but has a few minor differences in render output.

Things which are not rendered anymore by default:

- empty image classes
- empty optional elements (with display: none style)
- comments for hidden optional elements
- placeholders in unresolved include elements

You can still use the old renderer with `CheerioHtml({useLegacyRendering: true})` in your `contentType` configuration.

If you use custom outputFormatters which use the frameworks rendering you should switch them to `livingdoc.render()`. This gives you a big performance boost (10x - 20x faster) and ensures consistency with the new default of the CheerioHtml output renderer.

2021-03-30 07:25 UTC, gabrielhase commented on releases/release-2021-03.md
> +- 🔥 Remove coffee-script support in the webpack setup in the editor. We've dropped coffee-script a few years ago, but still kept the webpack loader as not all projects were migrated. From now on we'v
I am pretty sure Mainpost is still using it. But if that still works, it's fine

2021-03-30 07:26 UTC, gabrielhase approved these changes
👍

2021-03-30 07:28 UTC, merged